---
- hosts: development #you can choose any hosts gruop name|all|ip|patterns

  user: vagrant

  gather_facts: yes # send fact from remote host. if "no" you can't use variables from remote host like "ohai_fqdn"
                    # to show host name
  roles:
    - ideato.common
    - ideato.webserver
    - ideato.database.mysql
    - project.build

  vars_files:
    - vars/common.yml

  sudo: True
