---
- hosts: development

  user: vagrant

  vars_files:
    - host_vars/development.yml

  gather_facts: yes

  roles:
    - ideato.common
    - ideato.webserver
    # - ideato.database.mysql

  become: True
