---
- hosts: development

  user: vagrant

  vars:
    - synced_folder: "{{ synced_folder }}"
    - host: "{{ host }}"

  vars_files:
    - host_vars/development.yml

  gather_facts: yes

  roles:
    - ideato.common
    - ideato.webserver
    - ideato.database.mysql
    - ideato.nodejs
    - ideato.elasticsearch

  become: True
