---

- name: copy all dotfiles to vagrant home
  copy: src={{ item }} dest=/home/vagrant/
  with_fileglob:
    - dot/.bash*

- name: install common package
  yum: name={{ item }} state=present
  with_items:
    - git
    - curl
    - vim
    - gcc
    - zlib
    - zlib-devel
    - zlib-static
    - openssl-devel
    - cachefilesd
    - ntp

- name: cachefilesd
  shell: echo "RUN=yes" > /etc/default/cachefilesd

- name: cachefilesd start service
  service: name=cachefilesd enabled=yes state=restarted

- name: restart ntpd
  service: name=ntpd enabled=yes state=restarted
