---

- name: copy all dotfiles to vagrant home
  copy: src={{ item }} dest=/home/vagrant/
  with_fileglob:
    - dot/.git-*
    - dot/.bash*

- name: install common package
  apt: name={{ item }} state=present
  with_items:
    - git
    - curl
    - vim
    
- name: Set SYMFONY__USE_SHM environment variable
  lineinfile: dest=/etc/environment line='SYMFONY__USE_SHM="true"'
